export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';

export const FETCH_RESULTS = 'FETCH_RESULTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_RESULT_DETAILS = 'FETCH_RESULT_DETAILS';
export const SET_FETCH_RESULTS = 'SET_FETCH_RESULTS';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SORTING_CRITERIA = 'SET_SORTING_CRITERIA';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_RESULT_DETAILS = 'SET_RESULT_DETAILS';
export const ADD_RESULT_ITEM = 'ADD_RESULT_ITEM';
export const SET_RESULT_ITEMS = 'SET_RESULT_ITEMS';
export const SET_IS_FETCHING_DATA = 'SET_IS_FETCHING_DATA';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
