// API TYPES
export const API_START = 'API_START';
export const API_END = 'API_END';
export const API_ERROR = 'API_ERROR';

// APP TYPES
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_QUESTION_INDEX = 'SET_QUESTION_INDEX';
export const INCREMENT_CORRECT_ANSWERS = 'INCREMENT_CORRECT_ANSWERS';
export const RESET_CORRECT_ANSWERS = 'RESET_CORRECT_ANSWERS';
export const SET_USER_ANSWER = 'SET_USER_ANSWER';
export const RESET_USER_ANSWERS = 'RESET_USER_ANSWERS';
